image: node:8.12.0-jessie

before_script:
  - node -v
  - npm -v
  - npm install

stages:
  - deploy


pages:
  stage: deploy
  script:
    - npm run deploy
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - public
  only:
    - master