image: node:8.12.0-jessie

before_script:
  - node -v
  - npm -v

stages:
  - build 
  - production

build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
      - public
  cache:
    paths:
      - node_modules

production:
  stage: production 
  image: ruby:latest
  script: 
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=isemaj-timestamp-microservice --api-key=$HEROKU_API_KEY
  only:
    - master


